# Where function 

✅ What is np.where() in NumPy?

np.where() is a conditional function that allows you to:

* ✔️ Find positions (indexes) where a condition is True
* ✔️ Replace values based on a condition
* ✔️ Apply if–else logic to arrays

In [4]:
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# find position(index) where the condtion is true 

In [6]:
np.where(arr > 5)

(array([5, 6, 7, 8, 9]),)

In [11]:
# replace the value based of condtion 
print(np.where(arr > 5,1,0))
print(np.where(arr > 5,1,arr))

[0 0 0 0 0 1 1 1 1 1]
[1 2 3 4 5 1 1 1 1 1]


In [13]:
np.where(arr == 5,100,arr)

array([  1,   2,   3,   4, 100,   6,   7,   8,   9,  10])

In [ ]:
np.where((arr > 2) & (arr < 5),'yes','n')