# Where function 

✅ What is np.where() in NumPy?

np.where() is a conditional function that allows you to:

* ✔️ Find positions (indexes) where a condition is True
* ✔️ Replace values based on a condition
* ✔️ Apply if–else logic to arrays

In [5]:
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# find position(index) where the condtion is true 

In [6]:
np.where(arr > 5)

(array([5, 6, 7, 8, 9]),)

In [115]:
ar = np.random.randint(0,10,10)
print(ar)
result = np.where(ar>5)
print(result)

[2 3 7 9 0 2 6 5 5 5]
(array([2, 3, 6]),)


In [116]:
print(ar[np.where(ar>5)])

[7 9 6]


In [11]:
# replace the value based of condtion 
print(np.where(arr > 5,1,0))
print(np.where(arr > 5,1,arr))

[0 0 0 0 0 1 1 1 1 1]
[1 2 3 4 5 1 1 1 1 1]


In [13]:
np.where(arr == 5,100,arr)

array([  1,   2,   3,   4, 100,   6,   7,   8,   9,  10])

In [ ]:
np.where((arr > 2) & (arr < 5),'yes','n')

In [21]:
a = np.random.randint(1,10,2)
b = np.random.randint(1,10,2)
ab = np.concatenate((a,b), axis = 0)
print(ab)

[7 8 7 8]


In [57]:
print(np.split(ab,2))
print(ab)

[array([7, 8]), array([7, 8])]
[7 8 7 8]


In [71]:
sort = np.sort(ab)
print(sort)
decending = sort[::-1]
print(decending)

[7 7 8 8]
[8 8 7 7]
