# empty 

empty is a numpy fuction which is used for createing an array
withoth initialized its value.
they contain the random garbage values that alread exist in the memory

In [16]:
import numpy as np 
arr = np.empty((3,3) , dtype = int)
print(arr)

[[ 4607825790175356063 -4611042647052049244  4603322190547985584]
 [-4611042647052049245  4617283349392834113 -4613744806828471525]
 [ 4603322190547985580 -4613744806828471527  4606153024599475607]]


# linspace 
linspace is a numpy fuction which is used for creating an array with evenly space number between a start and end vlaues 

this fuction is similar to the arange fuction but insted of step size

In [18]:
ar = np.linspace(1,10)
print(ar)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [42]:
print(np.linspace(1,10,5 , endpoint = False))


[1.  2.8 4.6 6.4 8.2]


In [36]:
print(np.linspace(0,1,100))

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [46]:
print(np.linspace(0,10,5, retstep = True))

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))


In [47]:
print(np.linspace(0,10,5,retstep = True,endpoint = False))

(array([0., 2., 4., 6., 8.]), np.float64(2.0))
