# genrate random values with the help of random fuction 

In [8]:
import numpy as np 
ar = np.random.rand()
print(ar)

0.33505327522883543


# 1d

In [10]:
print(np.random.rand(5))

[0.60326052 0.43254121 0.47915066 0.63955681 0.13267977]


# 2d 

In [12]:
print(np.random.rand(5,5))

[[0.22017643 0.2275419  0.62100435 0.08440067 0.66806944]
 [0.10627591 0.04215085 0.02074763 0.16417435 0.90033353]
 [0.4186387  0.2353221  0.71886385 0.78604045 0.01161484]
 [0.29068463 0.57196229 0.13893634 0.67395305 0.75997491]
 [0.49002202 0.89219518 0.31860641 0.43466917 0.88374873]]


# random.randint is used for genrate the random integer values 
there are three major parameter that was the 
1. start
2. end
3. values (how much number you need in between the range of start to end values)

In [40]:
print(np.random.randint(0,7,3))
print(np.random.randint(1,10,10))

[2 0 4]
[5 6 7 7 3 5 4 2 7 6]
