# This question practic for the cybrom test 

Q.1 Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [1]:
import numpy as np 
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Q.2 Write a NumPy program to create a null vector of size 10 and update the sixth value to 5.

In [4]:
zero = np.zeros(10, dtype = int)
zero[4] = 5
print(zero)

[0 0 0 0 5 0 0 0 0 0]


Q.3 Write a NumPy program to reverse an array (the first element becomes the last).

In [5]:
ar = np.random.randint(1,10,6)
reverse = ar[::-1]
print(ar)
print(reverse)


[4 5 8 1 6 3]
[3 6 1 8 5 4]


Q.4 Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

In [27]:
m = np.zeros((8,8),dtype = int)
print(m)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [39]:
matrix = np.zeros((8,8) , dtype = int)
matrix[::2,1::2] = 1
matrix[1::2,::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q.5 Write a NumPy program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]

In [40]:
li = [1,2,3,4,5,6,7,8]
ar_li = np.array(li)
tu = ((8,4,6),(1,2,3))
ar_tu = np.array(tu)
print(f'{ar_li}\n {ar_tu}')

[1 2 3 4 5 6 7 8]
 [[8 4 6]
 [1 2 3]]


Q.6 Write a NumPy program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]

In [42]:
array1 = np.array([43,34,34,54,43])
array2 = np.array([34,43])
np.intersect1d(array1,array2)

array([34, 43])

Q.7 Write a NumPy program to get the unique elements of an array.
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]

In [44]:
a = np.array([10,10,20,20,30,30])
np.unique(a)

array([10, 20, 30])

Q.8 Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]

In [67]:
arr1 = np.array([0,54,20,90,60,80])
arr2 = np.array([20,30,40,50,10])
union = np.union1d(arr1,arr2)
print(union)

[ 0 10 20 30 40 50 54 60 80 90]


In [70]:
reverse = union[::-1]
print(reverse)

[90 80 60 54 50 40 30 20 10  0]


Q.9 Write a NumPy program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]


In [115]:
ar = np.array([[10,20,30],[20,40,50]])
print(ar)
ar.ravel()


[[10 20 30]
 [20 40 50]]


array([10, 20, 30, 20, 40, 50])

10 Write a NumPy program to create another shape from an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [132]:
or_reshape = np.arange(1,7).reshape(3,2)
print(or_reshape)
print()
print(or_reshape.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]


Q.11 Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
Expected Output:
[[4 0 0 0]
[0 5 0 0]
[0 0 6 0]
[0 0 0 8]]

In [137]:
zeros = np.diag([4,5,6,8])
print(zeros)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [140]:
zeros.diagonal()

array([4, 5, 6, 8])


Q.12 Write a NumPy program to find the 4th element of a specified array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Forth e1ement of the array:
6

In [152]:
array_find_pos = np.array([[2,4,0],[6,8,10]])
print(array_find_pos)
array_find_pos[1,0]

[[ 2  4  0]
 [ 6  8 10]]


np.int64(6)

# Practice shell

In [175]:
zeros = np.zeros((5,5))
print(zeros)
ones = np.ones((5,5) , dtype = int)
print(ones)
fill_number = np.full((5,5),18)
print(fill_number)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


In [183]:
arr = np.arange(1,10)
float_ar = arr.astype(float)
print(arr)
print(float_ar)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [186]:
print(np.eye((5)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [230]:
print(np.empty((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Upcoming question will be soon 

In [1]:
dskahf klahf sdhf skf kh dshf dsdhfdo oofhs dgg 

SyntaxError: invalid syntax (1897610376.py, line 1)

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [4]:
ds = sns.load_dataset('tips')
ds

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]