Q.1 How to import pandas and check the version?

In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
pd.__version__
np.__version__
sns.__version__

'0.13.2'

Q.2  How to create a series from a list, numpy array and dict?


In [13]:
li = ['a','b','c','d','e']
print(pd.Series(li))

ar = np.array(['dsfs','fd','dsf'])
print(pd.Series(ar))

dic = {'name':['yash','suraj','rani','tushar'],
      'marks':[99,78,98,00,89]}
pd.Series(dic)

0    a
1    b
2    c
3    d
4    e
dtype: object
0    dsfs
1      fd
2     dsf
dtype: object


name     [yash, suraj, rani, tushar]
marks            [99, 78, 98, 0, 89]
dtype: object

Q.3 How to convert the index of a series into a column of a dataframe?

# reset_index()

In [35]:
series = pd.Series([3,4,5], index = ['a','b','c'])
print(series)
series.reset_index()

a    3
b    4
c    5
dtype: int64


index  0
0     a  3
1     b  4
2     c  5

Q.4 How to get the items not common to both series A and series B?

In [52]:
s = pd.Series([1,2,3,4,5])
s1 = pd.Series([1,5,90,32,67])
pd.concat([s,s1])

0     1
1     2
2     3
3     4
4     5
0     1
1     5
2    90
3    32
4    67
dtype: int64

In [59]:
pd.concat([s[~s.isin(s1)],s1[~s1.isin(s)]]) # this line is showing the not common element 

1     2
2     3
3     4
2    90
3    32
4    67
dtype: int64

In [60]:
pd.concat([s[s.isin(s1)],s1[s1.isin(s)]]) # show the common element 

0    1
4    5
0    1
1    5
dtype: int64

In [4]:
ar = np.array([1,2,3,4,5]).reshape(1,5)
print(ar)

[[1 2 3 4 5]]


In [7]:
ar = np.array([1,2,3,4,5] , ndmin = 2)
print(ar)

[[1 2 3 4 5]]


In [23]:
np.delete(ar,3)

array([1, 2, 3, 5])

In [126]:
arrr = np.random.randint(1,10,4).reshape(2,2)
print(arrr)
np.delete(arrr,1)

[[4 3]
 [3 1]]


array([4, 3, 1])

In [127]:
arr = np.array([[1,2,3,5,4,8],[8,4,7,5,6,9]])
print("remove for the 2d :-")
print(np.delete(arr,1,axis=0))

remove for the 2d :-
[[1 2 3 5 4 8]]


In [159]:
a = np.linspace(1,100,5)
b = np.linspace(0,50,5) #endpoint = False,retstep = True)
np.concatenate((a,b))

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ,   0.  ,  12.5 ,  25.  ,
        37.5 ,  50.  ])

In [186]:
a_1 = np.array([1,2,3,4,9,6])
np.split(a_1,3)

[array([1, 2]), array([3, 4]), array([9, 6])]

In [185]:
v_array =   np.array([[0,1,2,3,4],
                      [5,7,8,9,4]])
print(np.vsplit(v_array,2))

[array([[0, 1, 2, 3, 4]]), array([[5, 7, 8, 9, 4]])]


In [240]:
print(np.sort(a_1))
print(a_1[::-1])

[1 2 3 4 6 9]
[6 9 4 3 2 1]


In [241]:
a = np.array([1,2,3,4])
a = np.append(a,np.nan)
print(a)


[ 1.  2.  3.  4. nan]


In [216]:
# fill the none value 
np.nan_to_num(a,nan = 5)

array([1., 2., 3., 4., 5.])

In [233]:
a = np.array([1,2,3,4,np.inf,-np.inf])
np.nan_to_num(a,posinf = 5,neginf = 5)

array([1., 2., 3., 4., 5., 5.])

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
import _strptime %%SVG %%HTML

SyntaxError: invalid syntax (3345280040.py, line 1)

In [2]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()