# Numpy qustion 

# Q.1 Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [1]:
import numpy as np 
array = np.arange(2,11).reshape(3,3)
print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Q.2 Write a NumPy program to create a null vector of size 10 and update the sixth value to 5.

* [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
*  Update sixth value to 5
* [ 0. 0. 0. 0. 0. 5 0. 0. 0. 0.]

In [2]:
arr = np.zeros(10)
arr[4] = 5
print(arr)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


# Q.3 Write a NumPy program to reverse an array (the first element becomes the last).

* Original array:
* [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

* Reverse array:
* [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [4]:
arr = np.array([12 ,13 ,14 ,15 ,16 ,17 ,18 ,19 ,20 ,21 ,22 ,23 ,24 ,25 ,26 ,27, 28, 29 ,30 ,31 ,32 ,33 ,34, 35 ,36 ,37])
arr = arr[::-1]
print(arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


# Q.4 Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

In [26]:
arr = np.zeros((8,8) ,dtype= int)
arr[1::2,::2] = 1 
arr[::2,1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Q.5 Write a NumPy program to convert a list and tuple into arrays.
* List to array:
[1 2 3 4 5 6 7 8]
* Tuple to array:
[[8 4 6]
[1 2 3]]

In [32]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
arr1 = np.array(((8,4,6),(1,2,3)))
print(arr1)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [31]:
li =[1,2,3,4,5,6,7,8]
tu = ((8,4,6),(1,2,3))
arr = np.array(li)
arr1 = np.array(tu)
print(f'{arr}\n{arr1}')

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


# Q.6 Write a NumPy program to find common values between two arrays.
* Expected Output:
* Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
* Common values between two arrays:
[10 40]

In [33]:
array = np.array([0,10,20,40,60])
array1 = np.array([10,30,40])
common_element = np.intersect1d(array,array1)
print(common_element)

[10 40]


# Q.7 Write a NumPy program to get the unique elements of an array.
* Expected Output:
* Original array:
* [10 10 20 20 30 30]
* Unique elements of the above array:
[10 20 30]

In [40]:
a = np.array([10,10,20,20,30,30])
print(np.unique(a))
print(np.unique_counts(a))
print(np.unique_all(a))
print(np.unique_values(a))

[10 20 30]
UniqueCountsResult(values=array([10, 20, 30]), counts=array([2, 2, 2]))
UniqueAllResult(values=array([10, 20, 30]), indices=array([0, 2, 4]), inverse_indices=array([0, 0, 1, 1, 2, 2]), counts=array([2, 2, 2]))
[30 20 10]


Q.8 Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]

In [41]:
a = np.array([0,10,20,40,60,80])
b = np.array([10,30,40,50,70])
np.union1d(a,b)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

Q.9 Write a NumPy program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [71]:
arr = np.array([[10,20,30],
               [20,40,50]])
print(arr.ravel())
print(arr.flatten())

[10 20 30 20 40 50]
[10 20 30 20 40 50]


10 Write a NumPy program to create another shape from an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [74]:
array_ = np.array([[1,2],
                    [3,4],
                    [5,6]]) 
print(array_.reshape(2,3))


[[1 2 3]
 [4 5 6]]


Q.11 Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
Expected Output:
[[4 0 0 0]
[0 5 0 0]
[0 0 6 0]
[0 0 0 8]]

In [90]:
diagonal = np.diag([4,5,6,8]) # diag this method fill the diagonal values as your requirments 
print(diagonal)
print('')
print(np.diagonal(diagonal)) # diagonal is extract the diagonal values 


[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]

[4 5 6 8]


Q.12 Write a NumPy program to find the 4th element of a specified array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Forth e1ement of the array:
6

In [94]:
find = np.array([[2,4,6]
                ,[6,8,10]])
print(find[1,0])

6


i'l soon back 

In [95]:
dsafhlsgd

NameError: name 'dsafhlsgd' is not defined

dgfldsag sdhfsfhs dff isuusiudgh sdilug sdi