# 🧠 What is KNN (K-Nearest Neighbors)?

* KNN stands for K-Nearest Neighbors.
* It is a supervised learning algorithm that predicts the output for a new data point based on the majority of its nearest neighbors in the training data.

# example

| Study Hours | Score | Result |
| ----------- | ----- | ------ |
| 1           | 20    | Fail   |
| 2           | 30    | Fail   |
| 3           | 50    | Pass   |
| 4           | 70    | Pass   |

* Now if a new student studied 2.5 hours, KNN looks at the K nearest points (say K=3) around 2.5 and checks their labels.
* 👉 If most of them are “Pass”, KNN predicts Pass.
* 👉 If most are “Fail”, KNN predicts Fail.

🧮 2️⃣ Mathematically

KNN uses distance (most commonly Euclidean distance) to find which data points are closest to the new one.

𝑑
=
(
𝑥
1
−
𝑥
2
)
2
+
(
𝑦
1
−
𝑦
2
)
2
d=
(x
1
	​

−x
2
	​

)
2
+(y
1
	​

−y
2
	​

)
2
	​


It calculates this distance between the new point and all points in the dataset.

# 🧩 6️⃣ Advantages

* ✅ Very simple and intuitive
* ✅ No training time — just stores the data
* ✅ Works for both classification and regression
* ✅ Non-parametric (makes no assumption about data distribution)

# ⚠️ 7️⃣ Disadvantages

* ❌ Slow for large datasets (distance calculation for every new point)
* ❌ Sensitive to irrelevant features and feature scaling
* ❌ Choosing “K” is tricky (too small → noisy, too large → inaccurate) 

In [1]:
import numpy as np 
from sklearn.neighbors import KNeighborsClassifier
# data
x = np.array([[180,7],[200,7.5],[250,8],[300,8.5],[350,9]])
y = np.random.randint(0,2,5)

# model 
model = KNeighborsClassifier(n_neighbors=3)
model = model.fit(x,y)

weight = float(input("enter your weight :-"))
size = float(input("enter your size :-"))
print(y)
predection = model.predict([[weight,size]])[0]
if predection == 1:
    print('orange')
else:
    print('apple')

enter your weight :- 250
enter your size :- 8.4


[0 1 0 0 0]
apple


In [1]:
import numpy as np

arr = np.array([10, 25, 40, 55, 75, 90])

# Use & for AND condition
result = np.where((arr > 30) & (arr < 70))
print(result)


(array([2, 3], dtype=int64),)


In [3]:
k  = np.where(arr>0,1,arr)
print(k)

[1 1 1 1 1 1]
